name: web_fashion
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.7
  file_picker: ^4.3.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/produtos/